### ISSUE TITLE
Parser fails for string "\\" and similar values

### ISSUE THREAD

**Issue by richard-gebbia** [Bogdanp/elm-ast#34]
The following declaration in the parser:

```elm
x = "\\"
```
shows the following error:
(Err (["expected end of input"]),{ input = "x = \"\\\\\"\n", position = 0 })

In fact, any number of backslashes followed by a single quote fails to parse. While some of those are legitimate errors (odd numbers of backslashes), others aren't (even numbers of backslashes).

**Comment by richard-gebbia** [comment]
I believe this regex might work for your string parser "(\\\\\"|\\\\\\\\|[^\"\n])*" (not sure, though, parsing strings is hard :) )

**Comment by wende** [comment]
@richard-gebbia Thanks!
That's a great find and a very important bug
