### ISSUE TITLE
Parse tuple constructor (,)

### ISSUE THREAD

**Issue by tunguski** [Bogdanp/elm-ast#51]
Below is an example from List module. 

```elm
toIndexedList : Array a -> List (Int, a)
toIndexedList array =
  List.map2
    (,)
    (List.range 0 (Native.Array.length array - 1))
    (Native.Array.toList array)
```

**Comment by wende** [comment]
I'm pretty sure it works. There is a problem with example not getting updated, which I cannot get to because the reports are to @Bogdanp's email.

**Comment by wende** [comment]
Oh. Actually I am wrong. #38 broke that functionality. Good find!
