### ISSUE TITLE
Parse error on names starting with `as`

### ISSUE THREAD

**Issue by tunguski** [Bogdanp/elm-ast#64]
I've found parsing error on some simple code in my fork and tested that this project suffers it too (as long as example page is up to date). This example is extracted from Html module:

```elm
node =
  VirtualDom.node

aside =
  node "aside"
```

Even simpler (seems same case):

```elm
node = 0
aside = 7
```

What's interesting after switching order of functions code parses correctly.

**Comment by wende** [comment]
Good find. It appears, that when a name starts with `as` it recognizes it as an `as` operator when it shouldn't

**Comment by wende** [comment]
Moved to #72
