### ISSUE TITLE
Parsing error when pattern matching with a variable named alias

### ISSUE THREAD

**Issue by jfmengels** [Bogdanp/elm-ast#65]
Hi! First of all, thanks for making/picking up the package! :heart: 

I noticed that parsing fails when I'm pattern matching, and I named one of the variables `alias` (which is valid Elm code).

This fails:
```elm
fn param =
  case param of
    A alias -> 1
    B -> 2
```
This works:
```elm
fn param =
  case param of
    A aliass -> 1
    B -> 2
```

**Comment by wende** [comment]
It's the same as #72 closing
