### ISSUE TITLE
Only allow pair (Maybe FunctionTypeDeclaration, FunctionDeclaration) as Statement ?

### ISSUE THREAD

**Issue by desmond-dsouza** [Bogdanp/elm-ast#66]
Since a `FunctionTypeDeclaration` without a corresponding `FunctionDeclaration` is not legal (syntax?) in Elm, would it be useful to change:
```
type Statement
    = ...
    | FunctionTypeDeclaration Name Type
    | FunctionDeclaration Name (List Expression) Expression
    | ...
```
to:
```
type alias FunctionTypeDeclaration = FunctionTypeDeclaration Name Type
type alias FunctionDeclaration = FunctionDeclaration Name (List Expression) Expression
type Statement
    = ...
    | FunctionDefinition 
           (Maybe FunctionTypeDeclaration, FunctionDeclaration)
    | ...
```
with corresponding tweak to parser rules?

**Comment by joonazan** [comment]
There are countless cases like this. There needs to be another layer on top
of the parser that outputs a representation that disallows invalid syntax.

**Comment by desmond-dsouza** [comment]
ok, thanks for the feedback

**Comment by wende** [comment]
Closing since it's very disruptive and it yields little value
